### PR TITLE
adds support for thoughtbot's refills flashes

### PR DESCRIPTION
**Pull request by hwhelchel**
Hey @aexmachina I'd like to add support for thoughtbot's [refills](http://refills.bourbon.io/components) flash stylings. Here's what the error message looks like:

screen shot 2015-07-11 at 12 44 16 am

Would you be willing to accept this PR? Thanks!

### CODE REVIEW

**Comment by aexmachina** [comment]
Nice. Can you also add it to the README please.

**Comment by hwhelchel** [comment]
yep i'll do so now

**Comment by hwhelchel** [comment]
@aexmachina readme updated. cheers

**Comment by aexmachina** [comment]
Cool, thanks!

**Comment by aexmachina** [comment]
Published v3.4.0

**Pull request merged**
